import type { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { registerProfileTools } from './profiles.js';
import { registerSPCampaignTools } from './sp/campaigns.js';
import { registerSPAdGroupTools } from './sp/ad-groups.js';
import { registerSPKeywordTools } from './sp/keywords.js';
import { registerSPTargetTools } from './sp/targets.js';
import { registerSPProductAdTools } from './sp/product-ads.js';
import { registerSBCampaignTools } from './sb/campaigns.js';
import { registerSBAdGroupTools } from './sb/ad-groups.js';
import { registerSBKeywordTools } from './sb/keywords.js';
import { registerSDCampaignTools } from './sd/campaigns.js';
import { registerSDAdGroupTools } from './sd/ad-groups.js';
import { registerSDTargetTools } from './sd/targets.js';
import { registerSPReportTools } from './reports/sp-reports.js';
import { registerSBReportTools } from './reports/sb-reports.js';
import { registerSDReportTools } from './reports/sd-reports.js';
import { registerSPWriteTools } from './writes/sp-writes.js';
import { registerSBWriteTools } from './writes/sb-writes.js';
import { registerSDWriteTools } from './writes/sd-writes.js';
import { registerNegativeTools } from './negative.js';
import { registerSPKeywordSuggestionsTools } from './optimization/sp-keyword-suggestions.js';
import { registerSBKeywordSuggestionsTools } from './optimization/sb-keyword-suggestions.js';
import { registerCampaignAnalysisTools } from './optimization/campaign-analysis.js';
import { registerNegativeKeywordTools } from './optimization/negative-keywords.js';
import { registerAcosBreakdownTools } from './optimization/acos-breakdown.js';
import { registerCrossMcpTools } from './cross-mcp/correlate-reports.js';
import { registerTacosTools } from './cross-mcp/tacos.js';
import { registerOrganicVsAdTools } from './cross-mcp/organic-vs-ad.js';
import { registerSBCreativeTools } from './sb-creative.js';
import { registerRecommendationsTools } from './recommendations.js';
import { registerPortfolioTools } from './portfolios.js';

export function registerAllAdsTools(server: McpServer): void {
  registerProfileTools(server);
  registerSPCampaignTools(server);
  registerSPAdGroupTools(server);
  registerSPKeywordTools(server);
  registerSPTargetTools(server);
  registerSPProductAdTools(server);
  registerSBCampaignTools(server);
  registerSBAdGroupTools(server);
  registerSBKeywordTools(server);
  registerSDCampaignTools(server);
  registerSDAdGroupTools(server);
  registerSDTargetTools(server);
  registerSPReportTools(server);
  registerSBReportTools(server);
  registerSDReportTools(server);
  registerSPWriteTools(server);
  registerSBWriteTools(server);
  registerSDWriteTools(server);
  registerNegativeTools(server);
  registerSPKeywordSuggestionsTools(server);
  registerSBKeywordSuggestionsTools(server);
  registerCampaignAnalysisTools(server);
  registerNegativeKeywordTools(server);
  registerAcosBreakdownTools(server);
  registerCrossMcpTools(server);
  registerTacosTools(server);
  registerOrganicVsAdTools(server);
  registerSBCreativeTools(server);
  registerRecommendationsTools(server);
  registerPortfolioTools(server);
}
